<template>
    <div>
        <div class="page-box">
            <h2 class="_title">Icon 图标</h2>
            <p class="_descript">提供了一套常用的图标集合。</p>
            <dd-block title="基础用法" :code="code1">
                <template #source>
                    <dd-icon icon="icon-map"></dd-icon>
                    <dd-icon icon="icon-prompt"></dd-icon>
                    <dd-icon icon="icon-shangchuan"></dd-icon>
                    <dd-button type="primary" icon="icon-search"
                        >搜索</dd-button
                    >
                </template>
            </dd-block>
            <h3 class="_title">图标合集</h3>
            <ul class="icon-list">
              <li><dd-icon icon="icon-auto"></dd-icon><div><span>icon-auto</span></div></li>
              <li><dd-icon icon="icon-all"></dd-icon><div><span>icon-all</span></div></li>
              <li><dd-icon icon="icon-bussiness-man"></dd-icon><div><span>icon-bussiness-man</span></div></li>
              <li><dd-icon icon="icon-component"></dd-icon><div><span>icon-component</span></div></li>
              <li><dd-icon icon="icon-code"></dd-icon><div><span>icon-code</span></div></li>
              <li><dd-icon icon="icon-copy"></dd-icon><div><span>icon-copy</span></div></li>
              <li><dd-icon icon="icon-dollar"></dd-icon><div><span>icon-dollar</span></div></li>
              <li><dd-icon icon="icon-history"></dd-icon><div><span>icon-history</span></div></li>
              <li><dd-icon icon="icon-editor"></dd-icon><div><span>icon-editor</span></div></li>
              <li><dd-icon icon="icon-data"></dd-icon><div><span>icon-data</span></div></li>
              <li><dd-icon icon="icon-gift"></dd-icon><div><span>icon-gift</span></div></li>
              <li><dd-icon icon="icon-integral"></dd-icon><div><span>icon-integral</span></div></li>
              <li><dd-icon icon="icon-nav-list"></dd-icon><div><span>icon-nav-list</span></div></li>
              <li><dd-icon icon="icon-pic"></dd-icon><div><span>icon-pic</span></div></li>
              <li><dd-icon icon="icon-Notvisible"></dd-icon><div><span>icon-Notvisible</span></div></li>
              <li><dd-icon icon="icon-play"></dd-icon><div><span>icon-play</span></div></li>
              <li><dd-icon icon="icon-rising"></dd-icon><div><span>icon-rising</span></div></li>
              <li><dd-icon icon="icon-QRcode"></dd-icon><div><span>icon-QRcode</span></div></li>
              <li><dd-icon icon="icon-rmb"></dd-icon><div><span>icon-rmb</span></div></li>
              <li><dd-icon icon="icon-similar-product"></dd-icon><div><span>icon-similar-product</span></div></li>
              <li><dd-icon icon="icon-Exportservices-fill"></dd-icon><div><span>icon-Exportservices-fill</span></div></li>
              <li><dd-icon icon="icon-earth"></dd-icon><div><span>icon-earth</span></div></li>
              <li><dd-icon icon="icon-all-fill"></dd-icon><div><span>icon-all-fill</span></div></li>
              <li><dd-icon icon="icon-favorites-fill"></dd-icon><div><span>icon-favorites-fill</span></div></li>
              <li><dd-icon icon="icon-integral-fill"></dd-icon><div><span>icon-integral-fill</span></div></li>
              <li><dd-icon icon="icon-namecard-fill"></dd-icon><div><span>icon-namecard-fill</span></div></li>
              <li><dd-icon icon="icon-pic-fill"></dd-icon><div><span>icon-pic-fill</span></div></li>
              <li><dd-icon icon="icon-play-fill"></dd-icon><div><span>icon-play-fill</span></div></li>
              <li><dd-icon icon="icon-prompt-fill"></dd-icon><div><span>icon-prompt-fill</span></div></li>
              <li><dd-icon icon="icon-stop-fill"></dd-icon><div><span>icon-stop-fill</span></div></li>
              <li><dd-icon icon="icon-column"></dd-icon><div><span>icon-column</span></div></li>
              <li><dd-icon icon="icon-add-account"></dd-icon><div><span>icon-add-account</span></div></li>
              <li><dd-icon icon="icon-column1"></dd-icon><div><span>icon-column1</span></div></li>
              <li><dd-icon icon="icon-add"></dd-icon><div><span>icon-add</span></div></li>
              <li><dd-icon icon="icon-agriculture"></dd-icon><div><span>icon-agriculture</span></div></li>
              <li><dd-icon icon="icon-years"></dd-icon><div><span>icon-years</span></div></li>
              <li><dd-icon icon="icon-add-cart"></dd-icon><div><span>icon-add-cart</span></div></li>
              <li><dd-icon icon="icon-arrow-right"></dd-icon><div><span>icon-arrow-right</span></div></li>
              <li><dd-icon icon="icon-arrow-left"></dd-icon><div><span>icon-arrow-left</span></div></li>
              <li><dd-icon icon="icon-apparel"></dd-icon><div><span>icon-apparel</span></div></li>
              <li><dd-icon icon="icon-arrow-up"></dd-icon><div><span>icon-arrow-up</span></div></li>
              <li><dd-icon icon="icon-ascending"></dd-icon><div><span>icon-ascending</span></div></li>
              <li><dd-icon icon="icon-ashbin"></dd-icon><div><span>icon-ashbin</span></div></li>
              <li><dd-icon icon="icon-atm"></dd-icon><div><span>icon-atm</span></div></li>
              <li><dd-icon icon="icon-bad"></dd-icon><div><span>icon-bad</span></div></li>
              <li><dd-icon icon="icon-attachent"></dd-icon><div><span>icon-attachent</span></div></li>
              <li><dd-icon icon="icon-browse"></dd-icon><div><span>icon-browse</span></div></li>
              <li><dd-icon icon="icon-beauty"></dd-icon><div><span>icon-beauty</span></div></li>
              <li><dd-icon icon="icon-atm-away"></dd-icon><div><span>icon-atm-away</span></div></li>
              <li><dd-icon icon="icon-assessed-badge"></dd-icon><div><span>icon-assessed-badge</span></div></li>
              <li><dd-icon icon="icon-bags"></dd-icon><div><span>icon-bags</span></div></li>
              <li><dd-icon icon="icon-calendar"></dd-icon><div><span>icon-calendar</span></div></li>
              <li><dd-icon icon="icon-cart-full"></dd-icon><div><span>icon-cart-full</span></div></li>
              <li><dd-icon icon="icon-calculator"></dd-icon><div><span>icon-calculator</span></div></li>
              <li><dd-icon icon="icon-cameraswitching"></dd-icon><div><span>icon-cameraswitching</span></div></li>
              <li><dd-icon icon="icon-cecurity-protection"></dd-icon><div><span>icon-cecurity-protection</span></div></li>
              <li><dd-icon icon="icon-category"></dd-icon><div><span>icon-category</span></div></li>
              <li><dd-icon icon="icon-close"></dd-icon><div><span>icon-close</span></div></li>
              <li><dd-icon icon="icon-certified-supplier"></dd-icon><div><span>icon-certified-supplier</span></div></li>
              <li><dd-icon icon="icon-cart-Empty"></dd-icon><div><span>icon-cart-Empty</span></div></li>
              <li><dd-icon icon="icon-color"></dd-icon><div><span>icon-color</span></div></li>
              <li><dd-icon icon="icon-conditions"></dd-icon><div><span>icon-conditions</span></div></li>
              <li><dd-icon icon="icon-confirm"></dd-icon><div><span>icon-confirm</span></div></li>
              <li><dd-icon icon="icon-company"></dd-icon><div><span>icon-company</span></div></li>
              <li><dd-icon icon="icon-ali-clould"></dd-icon><div><span>icon-ali-clould</span></div></li>
              <li><dd-icon icon="icon-password-visible"></dd-icon><div><span>icon-password-visible</span></div></li>
              <li><dd-icon icon="icon-credit-level"></dd-icon><div><span>icon-credit-level</span></div></li>
              <li><dd-icon icon="icon-coupons"></dd-icon><div><span>icon-coupons</span></div></li>
              <li><dd-icon icon="icon-connections"></dd-icon><div><span>icon-connections</span></div></li>
              <li><dd-icon icon="icon-cry"></dd-icon><div><span>icon-cry</span></div></li>
              <li><dd-icon icon="icon-costoms-alearance"></dd-icon><div><span>icon-costoms-alearance</span></div></li>
              <li><dd-icon icon="icon-clock"></dd-icon><div><span>icon-clock</span></div></li>
              <li><dd-icon icon="icon-CurrencyConverter"></dd-icon><div><span>icon-CurrencyConverter</span></div></li>
              <li><dd-icon icon="icon-cut"></dd-icon><div><span>icon-cut</span></div></li>
              <li><dd-icon icon="icon-Moneymanagement-fill"></dd-icon><div><span>icon-Moneymanagement-fill</span></div></li>
              <li><dd-icon icon="icon-descending"></dd-icon><div><span>icon-descending</span></div></li>
              <li><dd-icon icon="icon-double-arrow-right"></dd-icon><div><span>icon-double-arrow-right</span></div></li>
              <li><dd-icon icon="icon-customization"></dd-icon><div><span>icon-customization</span></div></li>
              <li><dd-icon icon="icon-double-arrow-left"></dd-icon><div><span>icon-double-arrow-left</span></div></li>
              <li><dd-icon icon="icon-discount"></dd-icon><div><span>icon-discount</span></div></li>
              <li><dd-icon icon="icon-download"></dd-icon><div><span>icon-download</span></div></li>
              <li><dd-icon icon="icon-default-template"></dd-icon><div><span>icon-default-template</span></div></li>
              <li><dd-icon icon="icon-eletrical"></dd-icon><div><span>icon-eletrical</span></div></li>
              <li><dd-icon icon="icon-electronics"></dd-icon><div><span>icon-electronics</span></div></li>
              <li><dd-icon icon="icon-etrical-equipm"></dd-icon><div><span>icon-etrical-equipm</span></div></li>
              <li><dd-icon icon="icon-ellipsis"></dd-icon><div><span>icon-ellipsis</span></div></li>
              <li><dd-icon icon="icon-email"></dd-icon><div><span>icon-email</span></div></li>
              <li><dd-icon icon="icon-falling"></dd-icon><div><span>icon-falling</span></div></li>
              <li><dd-icon icon="icon-filter"></dd-icon><div><span>icon-filter</span></div></li>
              <li><dd-icon icon="icon-furniture"></dd-icon><div><span>icon-furniture</span></div></li>
              <li><dd-icon icon="icon-folder"></dd-icon><div><span>icon-folder</span></div></li>
              <li><dd-icon icon="icon-feeds"></dd-icon><div><span>icon-feeds</span></div></li>
              <li><dd-icon icon="icon-hardware"></dd-icon><div><span>icon-hardware</span></div></li>
              <li><dd-icon icon="icon-help"></dd-icon><div><span>icon-help</span></div></li>
              <li><dd-icon icon="icon-good"></dd-icon><div><span>icon-good</span></div></li>
              <li><dd-icon icon="icon-Householdappliances"></dd-icon><div><span>icon-Householdappliances</span></div></li>
              <li><dd-icon icon="icon-form"></dd-icon><div><span>icon-form</span></div></li>
              <li><dd-icon icon="icon-image-text"></dd-icon><div><span>icon-image-text</span></div></li>
              <li><dd-icon icon="icon-hot"></dd-icon><div><span>icon-hot</span></div></li>
              <li><dd-icon icon="icon-inspection"></dd-icon><div><span>icon-inspection</span></div></li>
              <li><dd-icon icon="icon-leftbutton"></dd-icon><div><span>icon-leftbutton</span></div></li>
              <li><dd-icon icon="icon-jewelry"></dd-icon><div><span>icon-jewelry</span></div></li>
              <li><dd-icon icon="icon-ipad"></dd-icon><div><span>icon-ipad</span></div></li>
              <li><dd-icon icon="icon-leftarrow"></dd-icon><div><span>icon-leftarrow</span></div></li>
              <li><dd-icon icon="icon-kitchen"></dd-icon><div><span>icon-kitchen</span></div></li>
              <li><dd-icon icon="icon-inquiry-template"></dd-icon><div><span>icon-inquiry-template</span></div></li>
              <li><dd-icon icon="icon-link"></dd-icon><div><span>icon-link</span></div></li>
              <li><dd-icon icon="icon-libra"></dd-icon><div><span>icon-libra</span></div></li>
              <li><dd-icon icon="icon-loading"></dd-icon><div><span>icon-loading</span></div></li>
              <li><dd-icon icon="icon-listing-content"></dd-icon><div><span>icon-listing-content</span></div></li>
              <li><dd-icon icon="icon-lights"></dd-icon><div><span>icon-lights</span></div></li>
              <li><dd-icon icon="icon-logistics-icon"></dd-icon><div><span>icon-logistics-icon</span></div></li>
              <li><dd-icon icon="icon-messagecenter"></dd-icon><div><span>icon-messagecenter</span></div></li>
              <li><dd-icon icon="icon-mobile-phone"></dd-icon><div><span>icon-mobile-phone</span></div></li>
              <li><dd-icon icon="icon-manage-order"></dd-icon><div><span>icon-manage-order</span></div></li>
              <li><dd-icon icon="icon-move"></dd-icon><div><span>icon-move</span></div></li>
              <li><dd-icon icon="icon-Moneymanagement"></dd-icon><div><span>icon-Moneymanagement</span></div></li>
              <li><dd-icon icon="icon-namecard"></dd-icon><div><span>icon-namecard</span></div></li>
              <li><dd-icon icon="icon-map"></dd-icon><div><span>icon-map</span></div></li>
              <li><dd-icon icon="icon-Newuserzone"></dd-icon><div><span>icon-Newuserzone</span></div></li>
              <li><dd-icon icon="icon-multi-language"></dd-icon><div><span>icon-multi-language</span></div></li>
              <li><dd-icon icon="icon-office"></dd-icon><div><span>icon-office</span></div></li>
              <li><dd-icon icon="icon-notice"></dd-icon><div><span>icon-notice</span></div></li>
              <li><dd-icon icon="icon-ontimeshipment"></dd-icon><div><span>icon-ontimeshipment</span></div></li>
              <li><dd-icon icon="icon-office-supplies"></dd-icon><div><span>icon-office-supplies</span></div></li>
              <li><dd-icon icon="icon-password"></dd-icon><div><span>icon-password</span></div></li>
              <li><dd-icon icon="icon-operation"></dd-icon><div><span>icon-operation</span></div></li>
              <li><dd-icon icon="icon-packaging"></dd-icon><div><span>icon-packaging</span></div></li>
              <li><dd-icon icon="icon-online-tracking"></dd-icon><div><span>icon-online-tracking</span></div></li>
              <li><dd-icon icon="icon-packing-labeling"></dd-icon><div><span>icon-packing-labeling</span></div></li>
              <li><dd-icon icon="icon-phone"></dd-icon><div><span>icon-phone</span></div></li>
              <li><dd-icon icon="icon-pin"></dd-icon><div><span>icon-pin</span></div></li>
              <li><dd-icon icon="icon-logistic-logo"></dd-icon><div><span>icon-logistic-logo</span></div></li>
              <li><dd-icon icon="icon-print"></dd-icon><div><span>icon-print</span></div></li>
              <li><dd-icon icon="icon-product"></dd-icon><div><span>icon-product</span></div></li>
              <li><dd-icon icon="icon-machinery"></dd-icon><div><span>icon-machinery</span></div></li>
              <li><dd-icon icon="icon-process"></dd-icon><div><span>icon-process</span></div></li>
              <li><dd-icon icon="icon-prompt"></dd-icon><div><span>icon-prompt</span></div></li>
              <li><dd-icon icon="icon-reeor"></dd-icon><div><span>icon-reeor</span></div></li>
              <li><dd-icon icon="icon-reduce"></dd-icon><div><span>icon-reduce</span></div></li>
              <li><dd-icon icon="icon-Non-staplefood"></dd-icon><div><span>icon-Non-staplefood</span></div></li>
              <li><dd-icon icon="icon-rejected-order"></dd-icon><div><span>icon-rejected-order</span></div></li>
              <li><dd-icon icon="icon-resonserate"></dd-icon><div><span>icon-resonserate</span></div></li>
              <li><dd-icon icon="icon-remind"></dd-icon><div><span>icon-remind</span></div></li>
              <li><dd-icon icon="icon-responsetime"></dd-icon><div><span>icon-responsetime</span></div></li>
              <li><dd-icon icon="icon-return"></dd-icon><div><span>icon-return</span></div></li>
              <li><dd-icon icon="icon-paylater"></dd-icon><div><span>icon-paylater</span></div></li>
              <li><dd-icon icon="icon-Rightarrow"></dd-icon><div><span>icon-Rightarrow</span></div></li>
              <li><dd-icon icon="icon-RFQ-logo"></dd-icon><div><span>icon-RFQ-logo</span></div></li>
              <li><dd-icon icon="icon-save"></dd-icon><div><span>icon-save</span></div></li>
              <li><dd-icon icon="icon-scanning"></dd-icon><div><span>icon-scanning</span></div></li>
              <li><dd-icon icon="icon-security"></dd-icon><div><span>icon-security</span></div></li>
              <li><dd-icon icon="icon-salescenter"></dd-icon><div><span>icon-salescenter</span></div></li>
              <li><dd-icon icon="icon-seleted"></dd-icon><div><span>icon-seleted</span></div></li>
              <li><dd-icon icon="icon-searchcart"></dd-icon><div><span>icon-searchcart</span></div></li>
              <li><dd-icon icon="icon-raw"></dd-icon><div><span>icon-raw</span></div></li>
              <li><dd-icon icon="icon-service"></dd-icon><div><span>icon-service</span></div></li>
              <li><dd-icon icon="icon-share"></dd-icon><div><span>icon-share</span></div></li>
              <li><dd-icon icon="icon-signboard"></dd-icon><div><span>icon-signboard</span></div></li>
              <li><dd-icon icon="icon-shuffling-banner"></dd-icon><div><span>icon-shuffling-banner</span></div></li>
              <li><dd-icon icon="icon-Rightbutton"></dd-icon><div><span>icon-Rightbutton</span></div></li>
              <li><dd-icon icon="icon-sorting"></dd-icon><div><span>icon-sorting</span></div></li>
              <li><dd-icon icon="icon-sound-Mute"></dd-icon><div><span>icon-sound-Mute</span></div></li>
              <li><dd-icon icon="icon-Similarproducts"></dd-icon><div><span>icon-Similarproducts</span></div></li>
              <li><dd-icon icon="icon-sound-filling"></dd-icon><div><span>icon-sound-filling</span></div></li>
              <li><dd-icon icon="icon-suggest"></dd-icon><div><span>icon-suggest</span></div></li>
              <li><dd-icon icon="icon-stop"></dd-icon><div><span>icon-stop</span></div></li>
              <li><dd-icon icon="icon-success"></dd-icon><div><span>icon-success</span></div></li>
              <li><dd-icon icon="icon-supplier-features"></dd-icon><div><span>icon-supplier-features</span></div></li>
              <li><dd-icon icon="icon-switch"></dd-icon><div><span>icon-switch</span></div></li>
              <li><dd-icon icon="icon-survey"></dd-icon><div><span>icon-survey</span></div></li>
              <li><dd-icon icon="icon-template"></dd-icon><div><span>icon-template</span></div></li>
              <li><dd-icon icon="icon-text"></dd-icon><div><span>icon-text</span></div></li>
              <li><dd-icon icon="icon-suspended"></dd-icon><div><span>icon-suspended</span></div></li>
              <li><dd-icon icon="icon-task-management"></dd-icon><div><span>icon-task-management</span></div></li>
              <li><dd-icon icon="icon-tool"></dd-icon><div><span>icon-tool</span></div></li>
              <li><dd-icon icon="icon-Top"></dd-icon><div><span>icon-Top</span></div></li>
              <li><dd-icon icon="icon-smile"></dd-icon><div><span>icon-smile</span></div></li>
              <li><dd-icon icon="icon-textile-products"></dd-icon><div><span>icon-textile-products</span></div></li>
              <li><dd-icon icon="icon-tradealert"></dd-icon><div><span>icon-tradealert</span></div></li>
              <li><dd-icon icon="icon-topsales"></dd-icon><div><span>icon-topsales</span></div></li>
              <li><dd-icon icon="icon-tradingvolume"></dd-icon><div><span>icon-tradingvolume</span></div></li>
              <li><dd-icon icon="icon-training"></dd-icon><div><span>icon-training</span></div></li>
              <li><dd-icon icon="icon-upload"></dd-icon><div><span>icon-upload</span></div></li>
              <li><dd-icon icon="icon-RFQ-word"></dd-icon><div><span>icon-RFQ-word</span></div></li>
              <li><dd-icon icon="icon-viewlarger"></dd-icon><div><span>icon-viewlarger</span></div></li>
              <li><dd-icon icon="icon-viewgallery"></dd-icon><div><span>icon-viewgallery</span></div></li>
              <li><dd-icon icon="icon-vehivles"></dd-icon><div><span>icon-vehivles</span></div></li>
              <li><dd-icon icon="icon-trust"></dd-icon><div><span>icon-trust</span></div></li>
              <li><dd-icon icon="icon-warning"></dd-icon><div><span>icon-warning</span></div></li>
              <li><dd-icon icon="icon-warehouse"></dd-icon><div><span>icon-warehouse</span></div></li>
              <li><dd-icon icon="icon-shoes"></dd-icon><div><span>icon-shoes</span></div></li>
              <li><dd-icon icon="icon-video"></dd-icon><div><span>icon-video</span></div></li>
              <li><dd-icon icon="icon-viewlist"></dd-icon><div><span>icon-viewlist</span></div></li>
              <li><dd-icon icon="icon-set"></dd-icon><div><span>icon-set</span></div></li>
              <li><dd-icon icon="icon-store"></dd-icon><div><span>icon-store</span></div></li>
              <li><dd-icon icon="icon-tool-hardware"></dd-icon><div><span>icon-tool-hardware</span></div></li>
              <li><dd-icon icon="icon-vs"></dd-icon><div><span>icon-vs</span></div></li>
              <li><dd-icon icon="icon-toy"></dd-icon><div><span>icon-toy</span></div></li>
              <li><dd-icon icon="icon-sport"></dd-icon><div><span>icon-sport</span></div></li>
              <li><dd-icon icon="icon-creditcard"></dd-icon><div><span>icon-creditcard</span></div></li>
              <li><dd-icon icon="icon-contacts"></dd-icon><div><span>icon-contacts</span></div></li>
              <li><dd-icon icon="icon-checkstand"></dd-icon><div><span>icon-checkstand</span></div></li>
              <li><dd-icon icon="icon-aviation"></dd-icon><div><span>icon-aviation</span></div></li>
              <li><dd-icon icon="icon-Daytimemode"></dd-icon><div><span>icon-Daytimemode</span></div></li>
              <li><dd-icon icon="icon-infantmom"></dd-icon><div><span>icon-infantmom</span></div></li>
              <li><dd-icon icon="icon-discounts"></dd-icon><div><span>icon-discounts</span></div></li>
              <li><dd-icon icon="icon-invoice"></dd-icon><div><span>icon-invoice</span></div></li>
              <li><dd-icon icon="icon-insurance"></dd-icon><div><span>icon-insurance</span></div></li>
              <li><dd-icon icon="icon-nightmode"></dd-icon><div><span>icon-nightmode</span></div></li>
              <li><dd-icon icon="icon-usercenter"></dd-icon><div><span>icon-usercenter</span></div></li>
              <li><dd-icon icon="icon-unlock"></dd-icon><div><span>icon-unlock</span></div></li>
              <li><dd-icon icon="icon-vip"></dd-icon><div><span>icon-vip</span></div></li>
              <li><dd-icon icon="icon-wallet"></dd-icon><div><span>icon-wallet</span></div></li>
              <li><dd-icon icon="icon-landtransportation"></dd-icon><div><span>icon-landtransportation</span></div></li>
              <li><dd-icon icon="icon-voice"></dd-icon><div><span>icon-voice</span></div></li>
              <li><dd-icon icon="icon-exchangerate"></dd-icon><div><span>icon-exchangerate</span></div></li>
              <li><dd-icon icon="icon-contacts-fill"></dd-icon><div><span>icon-contacts-fill</span></div></li>
              <li><dd-icon icon="icon-years-fill"></dd-icon><div><span>icon-years-fill</span></div></li>
              <li><dd-icon icon="icon-add-cart-fill"></dd-icon><div><span>icon-add-cart-fill</span></div></li>
              <li><dd-icon icon="icon-add-fill"></dd-icon><div><span>icon-add-fill</span></div></li>
              <li><dd-icon icon="icon-ashbin-fill"></dd-icon><div><span>icon-ashbin-fill</span></div></li>
              <li><dd-icon icon="icon-calendar-fill"></dd-icon><div><span>icon-calendar-fill</span></div></li>
              <li><dd-icon icon="icon-bad-fill"></dd-icon><div><span>icon-bad-fill</span></div></li>
              <li><dd-icon icon="icon-bussiness-man-fill"></dd-icon><div><span>icon-bussiness-man-fill</span></div></li>
              <li><dd-icon icon="icon-atm-fill"></dd-icon><div><span>icon-atm-fill</span></div></li>
              <li><dd-icon icon="icon-cart-full-fill"></dd-icon><div><span>icon-cart-full-fill</span></div></li>
              <li><dd-icon icon="icon-cart-Empty-fill"></dd-icon><div><span>icon-cart-Empty-fill</span></div></li>
              <li><dd-icon icon="icon-cameraswitching-fill"></dd-icon><div><span>icon-cameraswitching-fill</span></div></li>
              <li><dd-icon icon="icon-atm-away-fill"></dd-icon><div><span>icon-atm-away-fill</span></div></li>
              <li><dd-icon icon="icon-certified-supplier-fill"></dd-icon><div><span>icon-certified-supplier-fill</span></div></li>
              <li><dd-icon icon="icon-calculator-fill"></dd-icon><div><span>icon-calculator-fill</span></div></li>
              <li><dd-icon icon="icon-clock-fill"></dd-icon><div><span>icon-clock-fill</span></div></li>
              <li><dd-icon icon="icon-ali-clould-fill"></dd-icon><div><span>icon-ali-clould-fill</span></div></li>
              <li><dd-icon icon="icon-color-fill"></dd-icon><div><span>icon-color-fill</span></div></li>
              <li><dd-icon icon="icon-coupons-fill"></dd-icon><div><span>icon-coupons-fill</span></div></li>
              <li><dd-icon icon="icon-cecurity-protection-fill"></dd-icon><div><span>icon-cecurity-protection-fill</span></div></li>
              <li><dd-icon icon="icon-credit-level-fill"></dd-icon><div><span>icon-credit-level-fill</span></div></li>
              <li><dd-icon icon="icon-default-template-fill"></dd-icon><div><span>icon-default-template-fill</span></div></li>
              <li><dd-icon icon="icon-CurrencyConverter-fill"></dd-icon><div><span>icon-CurrencyConverter-fill</span></div></li>
              <li><dd-icon icon="icon-Customermanagement-fill"></dd-icon><div><span>icon-Customermanagement-fill</span></div></li>
              <li><dd-icon icon="icon-discounts-fill"></dd-icon><div><span>icon-discounts-fill</span></div></li>
              <li><dd-icon icon="icon-Daytimemode-fill"></dd-icon><div><span>icon-Daytimemode-fill</span></div></li>
              <li><dd-icon icon="icon-exl-fill"></dd-icon><div><span>icon-exl-fill</span></div></li>
              <li><dd-icon icon="icon-cry-fill"></dd-icon><div><span>icon-cry-fill</span></div></li>
              <li><dd-icon icon="icon-email-fill"></dd-icon><div><span>icon-email-fill</span></div></li>
              <li><dd-icon icon="icon-filter-fill"></dd-icon><div><span>icon-filter-fill</span></div></li>
              <li><dd-icon icon="icon-folder-fill"></dd-icon><div><span>icon-folder-fill</span></div></li>
              <li><dd-icon icon="icon-feeds-fill"></dd-icon><div><span>icon-feeds-fill</span></div></li>
              <li><dd-icon icon="icon-gold-supplie-fill"></dd-icon><div><span>icon-gold-supplie-fill</span></div></li>
              <li><dd-icon icon="icon-form-fill"></dd-icon><div><span>icon-form-fill</span></div></li>
              <li><dd-icon icon="icon-camera-fill"></dd-icon><div><span>icon-camera-fill</span></div></li>
              <li><dd-icon icon="icon-good-fill"></dd-icon><div><span>icon-good-fill</span></div></li>
              <li><dd-icon icon="icon-image-text-fill"></dd-icon><div><span>icon-image-text-fill</span></div></li>
              <li><dd-icon icon="icon-inspection-fill"></dd-icon><div><span>icon-inspection-fill</span></div></li>
              <li><dd-icon icon="icon-hot-fill"></dd-icon><div><span>icon-hot-fill</span></div></li>
              <li><dd-icon icon="icon-company-fill"></dd-icon><div><span>icon-company-fill</span></div></li>
              <li><dd-icon icon="icon-discount-fill"></dd-icon><div><span>icon-discount-fill</span></div></li>
              <li><dd-icon icon="icon-insurance-fill"></dd-icon><div><span>icon-insurance-fill</span></div></li>
              <li><dd-icon icon="icon-inquiry-template-fill"></dd-icon><div><span>icon-inquiry-template-fill</span></div></li>
              <li><dd-icon icon="icon-leftbutton-fill"></dd-icon><div><span>icon-leftbutton-fill</span></div></li>
              <li><dd-icon icon="icon-listing-content-fill"></dd-icon><div><span>icon-listing-content-fill</span></div></li>
              <li><dd-icon icon="icon-logistic-logo-fill"></dd-icon><div><span>icon-logistic-logo-fill</span></div></li>
              <li><dd-icon icon="icon-manage-order-fill"></dd-icon><div><span>icon-manage-order-fill</span></div></li>
              <li><dd-icon icon="icon-multi-language-fill"></dd-icon><div><span>icon-multi-language-fill</span></div></li>
              <li><dd-icon icon="icon-logistics-icon-fill"></dd-icon><div><span>icon-logistics-icon-fill</span></div></li>
              <li><dd-icon icon="icon-Newuserzone-fill"></dd-icon><div><span>icon-Newuserzone-fill</span></div></li>
              <li><dd-icon icon="icon-nightmode-fill"></dd-icon><div><span>icon-nightmode-fill</span></div></li>
              <li><dd-icon icon="icon-office-supplies-fill"></dd-icon><div><span>icon-office-supplies-fill</span></div></li>
              <li><dd-icon icon="icon-notice-fill"></dd-icon><div><span>icon-notice-fill</span></div></li>
              <li><dd-icon icon="icon-mute"></dd-icon><div><span>icon-mute</span></div></li>
              <li><dd-icon icon="icon-order-fill"></dd-icon><div><span>icon-order-fill</span></div></li>
              <li><dd-icon icon="icon-paylater-fill"></dd-icon><div><span>icon-paylater-fill</span></div></li>
              <li><dd-icon icon="icon-phone-fill"></dd-icon><div><span>icon-phone-fill</span></div></li>
              <li><dd-icon icon="icon-online-tracking-fill"></dd-icon><div><span>icon-online-tracking-fill</span></div></li>
              <li><dd-icon icon="icon-pdf-fill"></dd-icon><div><span>icon-pdf-fill</span></div></li>
              <li><dd-icon icon="icon-pin-fill"></dd-icon><div><span>icon-pin-fill</span></div></li>
              <li><dd-icon icon="icon-product-fill"></dd-icon><div><span>icon-product-fill</span></div></li>
              <li><dd-icon icon="icon-rankinglist-fill"></dd-icon><div><span>icon-rankinglist-fill</span></div></li>
              <li><dd-icon icon="icon-reduce-fill"></dd-icon><div><span>icon-reduce-fill</span></div></li>
              <li><dd-icon icon="icon-reeor-fill"></dd-icon><div><span>icon-reeor-fill</span></div></li>
              <li><dd-icon icon="icon-resonserate-fill"></dd-icon><div><span>icon-resonserate-fill</span></div></li>
              <li><dd-icon icon="icon-remind-fill"></dd-icon><div><span>icon-remind-fill</span></div></li>
              <li><dd-icon icon="icon-Rightbutton-fill"></dd-icon><div><span>icon-Rightbutton-fill</span></div></li>
              <li><dd-icon icon="icon-RFQ-logo-fill"></dd-icon><div><span>icon-RFQ-logo-fill</span></div></li>
              <li><dd-icon icon="icon-RFQ-word-fill"></dd-icon><div><span>icon-RFQ-word-fill</span></div></li>
              <li><dd-icon icon="icon-searchcart-fill"></dd-icon><div><span>icon-searchcart-fill</span></div></li>
              <li><dd-icon icon="icon-salescenter-fill"></dd-icon><div><span>icon-salescenter-fill</span></div></li>
              <li><dd-icon icon="icon-save-fill"></dd-icon><div><span>icon-save-fill</span></div></li>
              <li><dd-icon icon="icon-security-fill"></dd-icon><div><span>icon-security-fill</span></div></li>
              <li><dd-icon icon="icon-Similarproducts-fill"></dd-icon><div><span>icon-Similarproducts-fill</span></div></li>
              <li><dd-icon icon="icon-signboard-fill"></dd-icon><div><span>icon-signboard-fill</span></div></li>
              <li><dd-icon icon="icon-service-fill"></dd-icon><div><span>icon-service-fill</span></div></li>
              <li><dd-icon icon="icon-shuffling-banner-fill"></dd-icon><div><span>icon-shuffling-banner-fill</span></div></li>
              <li><dd-icon icon="icon-supplier-features-fill"></dd-icon><div><span>icon-supplier-features-fill</span></div></li>
              <li><dd-icon icon="icon-store-fill"></dd-icon><div><span>icon-store-fill</span></div></li>
              <li><dd-icon icon="icon-smile-fill"></dd-icon><div><span>icon-smile-fill</span></div></li>
              <li><dd-icon icon="icon-success-fill"></dd-icon><div><span>icon-success-fill</span></div></li>
              <li><dd-icon icon="icon-sound-filling-fill"></dd-icon><div><span>icon-sound-filling-fill</span></div></li>
              <li><dd-icon icon="icon-suspended-fill"></dd-icon><div><span>icon-suspended-fill</span></div></li>
              <li><dd-icon icon="icon-tool-fill"></dd-icon><div><span>icon-tool-fill</span></div></li>
              <li><dd-icon icon="icon-task-management-fill"></dd-icon><div><span>icon-task-management-fill</span></div></li>
              <li><dd-icon icon="icon-unlock-fill"></dd-icon><div><span>icon-unlock-fill</span></div></li>
              <li><dd-icon icon="icon-trust-fill"></dd-icon><div><span>icon-trust-fill</span></div></li>
              <li><dd-icon icon="icon-vip-fill"></dd-icon><div><span>icon-vip-fill</span></div></li>
              <li><dd-icon icon="icon-Top-fill"></dd-icon><div><span>icon-Top-fill</span></div></li>
              <li><dd-icon icon="icon-voice-fill"></dd-icon><div><span>icon-voice-fill</span></div></li>
              <li><dd-icon icon="icon-warning-fill"></dd-icon><div><span>icon-warning-fill</span></div></li>
              <li><dd-icon icon="icon-warehouse-fill"></dd-icon><div><span>icon-warehouse-fill</span></div></li>
              <li><dd-icon icon="icon-zip-fill"></dd-icon><div><span>icon-zip-fill</span></div></li>
              <li><dd-icon icon="icon-trade-assurance-fill"></dd-icon><div><span>icon-trade-assurance-fill</span></div></li>
              <li><dd-icon icon="icon-vs-fill"></dd-icon><div><span>icon-vs-fill</span></div></li>
              <li><dd-icon icon="icon-template-fill"></dd-icon><div><span>icon-template-fill</span></div></li>
              <li><dd-icon icon="icon-packing-labeling-fill"></dd-icon><div><span>icon-packing-labeling-fill</span></div></li>
              <li><dd-icon icon="icon-brand-fill"></dd-icon><div><span>icon-brand-fill</span></div></li>
              <li><dd-icon icon="icon-collection"></dd-icon><div><span>icon-collection</span></div></li>
              <li><dd-icon icon="icon-consumption-fill"></dd-icon><div><span>icon-consumption-fill</span></div></li>
              <li><dd-icon icon="icon-collection-fill"></dd-icon><div><span>icon-collection-fill</span></div></li>
              <li><dd-icon icon="icon-brand"></dd-icon><div><span>icon-brand</span></div></li>
              <li><dd-icon icon="icon-rejected-order-fill"></dd-icon><div><span>icon-rejected-order-fill</span></div></li>
              <li><dd-icon icon="icon-homepage-ads-fill"></dd-icon><div><span>icon-homepage-ads-fill</span></div></li>
              <li><dd-icon icon="icon-homepage-ads"></dd-icon><div><span>icon-homepage-ads</span></div></li>
              <li><dd-icon icon="icon-scenes-fill"></dd-icon><div><span>icon-scenes-fill</span></div></li>
              <li><dd-icon icon="icon-scenes"></dd-icon><div><span>icon-scenes</span></div></li>
              <li><dd-icon icon="icon-similar-product-fill"></dd-icon><div><span>icon-similar-product-fill</span></div></li>
              <li><dd-icon icon="icon-topraning-fill"></dd-icon><div><span>icon-topraning-fill</span></div></li>
              <li><dd-icon icon="icon-consumption"></dd-icon><div><span>icon-consumption</span></div></li>
              <li><dd-icon icon="icon-topraning"></dd-icon><div><span>icon-topraning</span></div></li>
              <li><dd-icon icon="icon-gold-supplier"></dd-icon><div><span>icon-gold-supplier</span></div></li>
              <li><dd-icon icon="icon-messagecenter-fill"></dd-icon><div><span>icon-messagecenter-fill</span></div></li>
              <li><dd-icon icon="icon-quick"></dd-icon><div><span>icon-quick</span></div></li>
              <li><dd-icon icon="icon-writing"></dd-icon><div><span>icon-writing</span></div></li>
              <li><dd-icon icon="icon-docjpge-fill"></dd-icon><div><span>icon-docjpge-fill</span></div></li>
              <li><dd-icon icon="icon-jpge-fill"></dd-icon><div><span>icon-jpge-fill</span></div></li>
              <li><dd-icon icon="icon-gifjpge-fill"></dd-icon><div><span>icon-gifjpge-fill</span></div></li>
              <li><dd-icon icon="icon-bmpjpge-fill"></dd-icon><div><span>icon-bmpjpge-fill</span></div></li>
              <li><dd-icon icon="icon-tifjpge-fill"></dd-icon><div><span>icon-tifjpge-fill</span></div></li>
              <li><dd-icon icon="icon-pngjpge-fill"></dd-icon><div><span>icon-pngjpge-fill</span></div></li>
              <li><dd-icon icon="icon-home"></dd-icon><div><span>icon-home</span></div></li>
              <li><dd-icon icon="icon-sendinquiry-fill"></dd-icon><div><span>icon-sendinquiry-fill</span></div></li>
              <li><dd-icon icon="icon-comments-fill"></dd-icon><div><span>icon-comments-fill</span></div></li>
              <li><dd-icon icon="icon-account-fill"></dd-icon><div><span>icon-account-fill</span></div></li>
              <li><dd-icon icon="icon-feed-logo-fill"></dd-icon><div><span>icon-feed-logo-fill</span></div></li>
              <li><dd-icon icon="icon-feed-logo"></dd-icon><div><span>icon-feed-logo</span></div></li>
              <li><dd-icon icon="icon-home-fill"></dd-icon><div><span>icon-home-fill</span></div></li>
              <li><dd-icon icon="icon-add-select"></dd-icon><div><span>icon-add-select</span></div></li>
              <li><dd-icon icon="icon-sami-select"></dd-icon><div><span>icon-sami-select</span></div></li>
              <li><dd-icon icon="icon-camera"></dd-icon><div><span>icon-camera</span></div></li>
              <li><dd-icon icon="icon-arrow-down"></dd-icon><div><span>icon-arrow-down</span></div></li>
              <li><dd-icon icon="icon-account"></dd-icon><div><span>icon-account</span></div></li>
              <li><dd-icon icon="icon-comments"></dd-icon><div><span>icon-comments</span></div></li>
              <li><dd-icon icon="icon-favorites"></dd-icon><div><span>icon-favorites</span></div></li>
              <li><dd-icon icon="icon-order"></dd-icon><div><span>icon-order</span></div></li>
              <li><dd-icon icon="icon-search"></dd-icon><div><span>icon-search</span></div></li>
              <li><dd-icon icon="icon-trade-assurance"></dd-icon><div><span>icon-trade-assurance</span></div></li>
              <li><dd-icon icon="icon-tradingdata"></dd-icon><div><span>icon-tradingdata</span></div></li>
              <li><dd-icon icon="icon-microphone"></dd-icon><div><span>icon-microphone</span></div></li>
              <li><dd-icon icon="icon-txt"></dd-icon><div><span>icon-txt</span></div></li>
              <li><dd-icon icon="icon-xlsx"></dd-icon><div><span>icon-xlsx</span></div></li>
              <li><dd-icon icon="icon-banzhengfuwu"></dd-icon><div><span>icon-banzhengfuwu</span></div></li>
              <li><dd-icon icon="icon-cangku"></dd-icon><div><span>icon-cangku</span></div></li>
              <li><dd-icon icon="icon-daibancaishui"></dd-icon><div><span>icon-daibancaishui</span></div></li>
              <li><dd-icon icon="icon-jizhuangxiang"></dd-icon><div><span>icon-jizhuangxiang</span></div></li>
              <li><dd-icon icon="icon-jiaobiao"></dd-icon><div><span>icon-jiaobiao</span></div></li>
              <li><dd-icon icon="icon-kehupandian"></dd-icon><div><span>icon-kehupandian</span></div></li>
              <li><dd-icon icon="icon-dongtai"></dd-icon><div><span>icon-dongtai</span></div></li>
              <li><dd-icon icon="icon-daikuan"></dd-icon><div><span>icon-daikuan</span></div></li>
              <li><dd-icon icon="icon-shengyijing"></dd-icon><div><span>icon-shengyijing</span></div></li>
              <li><dd-icon icon="icon-jiehui"></dd-icon><div><span>icon-jiehui</span></div></li>
              <li><dd-icon icon="icon-fencengpeizhi"></dd-icon><div><span>icon-fencengpeizhi</span></div></li>
              <li><dd-icon icon="icon-shenqingjilu"></dd-icon><div><span>icon-shenqingjilu</span></div></li>
              <li><dd-icon icon="icon-shangchuanbeiandanzheng"></dd-icon><div><span>icon-shangchuanbeiandanzheng</span></div></li>
              <li><dd-icon icon="icon-shangchuan"></dd-icon><div><span>icon-shangchuan</span></div></li>
              <li><dd-icon icon="icon-kehuquanyi"></dd-icon><div><span>icon-kehuquanyi</span></div></li>
              <li><dd-icon icon="icon-suoxiao"></dd-icon><div><span>icon-suoxiao</span></div></li>
              <li><dd-icon icon="icon-quanyipeizhi"></dd-icon><div><span>icon-quanyipeizhi</span></div></li>
              <li><dd-icon icon="icon-shuangshen"></dd-icon><div><span>icon-shuangshen</span></div></li>
              <li><dd-icon icon="icon-tongguan"></dd-icon><div><span>icon-tongguan</span></div></li>
              <li><dd-icon icon="icon-tuishui"></dd-icon><div><span>icon-tuishui</span></div></li>
              <li><dd-icon icon="icon-tongguanshuju"></dd-icon><div><span>icon-tongguanshuju</span></div></li>
              <li><dd-icon icon="icon-kuaidiwuliu"></dd-icon><div><span>icon-kuaidiwuliu</span></div></li>
              <li><dd-icon icon="icon-wuliuchanpin"></dd-icon><div><span>icon-wuliuchanpin</span></div></li>
              <li><dd-icon icon="icon-waihuishuju"></dd-icon><div><span>icon-waihuishuju</span></div></li>
              <li><dd-icon icon="icon-xinxibar_shouji"></dd-icon><div><span>icon-xinxibar_shouji</span></div></li>
              <li><dd-icon icon="icon-xinwaizongyewu"></dd-icon><div><span>icon-xinwaizongyewu</span></div></li>
              <li><dd-icon icon="icon-wuliudingdan"></dd-icon><div><span>icon-wuliudingdan</span></div></li>
              <li><dd-icon icon="icon-zhongjianren"></dd-icon><div><span>icon-zhongjianren</span></div></li>
              <li><dd-icon icon="icon-xinxibar_zhanghu"></dd-icon><div><span>icon-xinxibar_zhanghu</span></div></li>
              <li><dd-icon icon="icon-yidatong"></dd-icon><div><span>icon-yidatong</span></div></li>
              <li><dd-icon icon="icon-zhuanyequanwei"></dd-icon><div><span>icon-zhuanyequanwei</span></div></li>
              <li><dd-icon icon="icon-zhanghucaozuo"></dd-icon><div><span>icon-zhanghucaozuo</span></div></li>
              <li><dd-icon icon="icon-xuanzhuandu"></dd-icon><div><span>icon-xuanzhuandu</span></div></li>
              <li><dd-icon icon="icon-tuishuirongzi"></dd-icon><div><span>icon-tuishuirongzi</span></div></li>
              <li><dd-icon icon="icon-AddProducts"></dd-icon><div><span>icon-AddProducts</span></div></li>
              <li><dd-icon icon="icon-ziyingyewu"></dd-icon><div><span>icon-ziyingyewu</span></div></li>
              <li><dd-icon icon="icon-addcell"></dd-icon><div><span>icon-addcell</span></div></li>
              <li><dd-icon icon="icon-background-color"></dd-icon><div><span>icon-background-color</span></div></li>
              <li><dd-icon icon="icon-cascades"></dd-icon><div><span>icon-cascades</span></div></li>
              <li><dd-icon icon="icon-beijing"></dd-icon><div><span>icon-beijing</span></div></li>
              <li><dd-icon icon="icon-bold"></dd-icon><div><span>icon-bold</span></div></li>
              <li><dd-icon icon="icon-zijin"></dd-icon><div><span>icon-zijin</span></div></li>
              <li><dd-icon icon="icon-eraser"></dd-icon><div><span>icon-eraser</span></div></li>
              <li><dd-icon icon="icon-centeralignment"></dd-icon><div><span>icon-centeralignment</span></div></li>
              <li><dd-icon icon="icon-click"></dd-icon><div><span>icon-click</span></div></li>
              <li><dd-icon icon="icon-aspjiesuan"></dd-icon><div><span>icon-aspjiesuan</span></div></li>
              <li><dd-icon icon="icon-flag"></dd-icon><div><span>icon-flag</span></div></li>
              <li><dd-icon icon="icon-falg-fill"></dd-icon><div><span>icon-falg-fill</span></div></li>
              <li><dd-icon icon="icon-Fee"></dd-icon><div><span>icon-Fee</span></div></li>
              <li><dd-icon icon="icon-filling"></dd-icon><div><span>icon-filling</span></div></li>
              <li><dd-icon icon="icon-Foreigncurrency"></dd-icon><div><span>icon-Foreigncurrency</span></div></li>
              <li><dd-icon icon="icon-guanliyuan"></dd-icon><div><span>icon-guanliyuan</span></div></li>
              <li><dd-icon icon="icon-language"></dd-icon><div><span>icon-language</span></div></li>
              <li><dd-icon icon="icon-leftalignment"></dd-icon><div><span>icon-leftalignment</span></div></li>
              <li><dd-icon icon="icon-extra-inquiries"></dd-icon><div><span>icon-extra-inquiries</span></div></li>
              <li><dd-icon icon="icon-Italic"></dd-icon><div><span>icon-Italic</span></div></li>
              <li><dd-icon icon="icon-pcm"></dd-icon><div><span>icon-pcm</span></div></li>
              <li><dd-icon icon="icon-reducecell"></dd-icon><div><span>icon-reducecell</span></div></li>
              <li><dd-icon icon="icon-rightalignment"></dd-icon><div><span>icon-rightalignment</span></div></li>
              <li><dd-icon icon="icon-pointerleft"></dd-icon><div><span>icon-pointerleft</span></div></li>
              <li><dd-icon icon="icon-subscript"></dd-icon><div><span>icon-subscript</span></div></li>
              <li><dd-icon icon="icon-square"></dd-icon><div><span>icon-square</span></div></li>
              <li><dd-icon icon="icon-superscript"></dd-icon><div><span>icon-superscript</span></div></li>
              <li><dd-icon icon="icon-tag-subscript"></dd-icon><div><span>icon-tag-subscript</span></div></li>
              <li><dd-icon icon="icon-danjuzhuanhuan"></dd-icon><div><span>icon-danjuzhuanhuan</span></div></li>
              <li><dd-icon icon="icon-Transfermoney"></dd-icon><div><span>icon-Transfermoney</span></div></li>
              <li><dd-icon icon="icon-under-line"></dd-icon><div><span>icon-under-line</span></div></li>
              <li><dd-icon icon="icon-xiakuangxian"></dd-icon><div><span>icon-xiakuangxian</span></div></li>
              <li><dd-icon icon="icon-shouqi"></dd-icon><div><span>icon-shouqi</span></div></li>
              <li><dd-icon icon="icon-zhankai"></dd-icon><div><span>icon-zhankai</span></div></li>
              <li><dd-icon icon="icon-tongxunlu"></dd-icon><div><span>icon-tongxunlu</span></div></li>
              <li><dd-icon icon="icon-yiguanzhugongyingshang"></dd-icon><div><span>icon-yiguanzhugongyingshang</span></div></li>
              <li><dd-icon icon="icon-goumaipianhao"></dd-icon><div><span>icon-goumaipianhao</span></div></li>
              <li><dd-icon icon="icon-Subscribe"></dd-icon><div><span>icon-Subscribe</span></div></li>
              <li><dd-icon icon="icon-becomeagoldsupplier"></dd-icon><div><span>icon-becomeagoldsupplier</span></div></li>
              <li><dd-icon icon="icon-new"></dd-icon><div><span>icon-new</span></div></li>
              <li><dd-icon icon="icon-free"></dd-icon><div><span>icon-free</span></div></li>
              <li><dd-icon icon="icon-cad-fill"></dd-icon><div><span>icon-cad-fill</span></div></li>
              <li><dd-icon icon="icon-robot"></dd-icon><div><span>icon-robot</span></div></li>
              <li><dd-icon icon="icon-block"></dd-icon><div><span>icon-block</span></div></li>
              <li><dd-icon icon="icon-shouhuoicon"></dd-icon><div><span>icon-shouhuoicon</span></div></li>
              <li><dd-icon icon="icon-triangle-down-fill"></dd-icon><div><span>icon-triangle-down-fill</span></div></li>
              <li><dd-icon icon="icon-triangle-up-fill"></dd-icon><div><span>icon-triangle-up-fill</span></div></li>
              <li><dd-icon icon="icon-triangle-left-fill"></dd-icon><div><span>icon-triangle-left-fill</span></div></li>
              <li><dd-icon icon="icon-triangle-right-fill"></dd-icon><div><span>icon-triangle-right-fill</span></div></li>
              <li><dd-icon icon="icon-github-fill"></dd-icon><div><span>icon-github-fill</span></div></li>
              <li><dd-icon icon="icon-fullscreen"></dd-icon><div><span>icon-fullscreen</span></div></li>
              <li><dd-icon icon="icon-fullscreen-exit"></dd-icon><div><span>icon-fullscreen-exit</span></div></li>
              <li><dd-icon icon="icon-warning-fill-1"></dd-icon><div><span>icon-warning-fill-1</span></div></li>
            </ul>
            <dd-footer left="Layout 布局" right="Button 按钮"></dd-footer>
        </div>
    </div>
</template>

<script>
export default {
    name: "Icon",
    data() {
        return {
            code1: `
                <dd-icon icon="icon-map"></dd-icon>
                <dd-icon icon="icon-prompt"></dd-icon>
                <dd-icon icon="icon-shangchuan"></dd-icon>
                <dd-button type="primary" icon="icon-search">搜索</dd-button>
            `,
        };
    },
};
</script>

<style lang="less" scoped>
.page-box {
    width: 100%;
    .dd-icon {
        color: #606266;
        margin: 0 20px;
        font-size: 2.5em;
        vertical-align: middle;
    }
    .dd-button {
        margin: 0 20px;
    }
    .icon-list {
        display: grid;
        grid-template-columns: repeat(auto-fill , minmax(15rem, 1fr));
        grid-auto-flow: row dense;
        border: 1px solid #eaeefb;
        border-radius: 4px;
        > li {
            display: flex;
            flex-wrap: wrap;
            flex-direction: column;
            align-items: center;
            justify-content: space-evenly;
            // width: calc(100% / 6);
            text-align: center;
            height: 120px;
            cursor: pointer;
            color: #666;
            border-right: 1px solid #eee;
            border-bottom: 1px solid #eee;
            margin-bottom: -1px;
            margin-right: -1px;
            transition: all .5s;
            .dd-icon {
                color: #606266;
                margin: 0 20px;
                font-size: 2.5em;
                vertical-align: middle;
                transform: scale(1);
                transition: all .5s;
            }
            &:hover {
                color: #5cb6ff;
                .dd-icon {
                  transform: scale(1.4);
                  color: #5cb6ff;
                }
            }
        }
    }
}
</style>
